# Generated by Django 3.1.1 on 2020-09-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
